spring:
  jackson:
    time-zone: "GMT+8"
    date-format: "yyyy-MM-dd HH:mm:ss"
  datasource:
    #url: jdbc:mysql://47.102.153.115:3306/artificial_intelligence?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    #url: jdbc:mysql://localhost:3306/artificial_intelligence?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    url: jdbc:mysql://112.124.18.177:3306/artificial_intelligence?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username : root
    password : Password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 每次运行程序，没有表会新建表，但是表内有数据不会被清空，只会更新表结构。
    show-sql: true #控制台显示sql
logging:
  file: log/log.log
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
